### ISSUE TITLE
Drop css from application.css.scss

### ISSUE THREAD

**Issue by joshuajansen** [firmhouse/Startblock#31]
https://github.com/rails/sass-rails/blob/1ddfbc9883d51a676d273822f42ca2c7023382ea/lib/sass/rails/importer.rb#L97

**Comment by jvanbaarsen** [comment]
:+1:

**Comment by jvanbaarsen** [comment]
@joshuajansen That means we just want to have a .scss extension?

**Comment by joshuajansen** [comment]
Yes, sir!
