### ISSUE TITLE
Disable auto generation of assets and helpers

### ISSUE THREAD

**Issue by jvanbaarsen** [firmhouse/Startblock#39]
When you currently generate a controller, you also get the empty stylesheet, javascript and helper file. In most cases you end up deleting them anyway. Lets disable this behaviour by default

**Comment by michiels** [comment]
Hmm I'm not sure if I'm fond of that. There is a reason those things get auto-generated. And that is that you use sane default for scoping your files in a structured manner. Maybe if you generate a resource to only do backend development, you end up removing them in your pull. But I think it makes sense to keep the Rails naming scheme as default for frontend development.

What do you think?

**Comment by jvanbaarsen** [comment]
@michiels Most of the time I end up creating a comment on a pull with the question "Can you please delete this file since you're not using it". I really feel very strongly about removing this files by default. Since when you're creating the backend code you don't directly need them, and the naming does not always map great to the actual usecase the files serve (thats mostly for JS). Helpers, I think we almost never use those files. So that means you only might need to create a SCSS file (in case you need them). I like defaults, but these defaults don't make sense to me.

**Comment by michiels** [comment]
Allright. Let's say I beg to differ because I use this feature a lot and you don't because you don't work in these files a lot. But I agree that the default mappings aren't always useful.

Since you feel strongly and you're the maintainer if this project. You go do your thing!

**Comment by jvanbaarsen** [comment]
@michiels Since we can also disable certain parts, what do you feel about just disabling the JS and helper files?

```
config.generators.stylesheets = false
config.generators.javascripts = false
config.generators.helper      = false
```

**Comment by joshuajansen** [comment]
I like the convention of matching the naming of helper/js/stylesheet. However, most of the time I find myself removing more files that I would be creating (also for front-end dev).

So I'm in favor of disabling by default, but keeping the default filenames/structure convention.

**Comment by joshuajansen** [comment]
@jvanbaarsen that would be a bit weird for devs not familiar with this discussion :smile: I'd say all or none.

**Comment by jvanbaarsen** [comment]
Ok, since its 2 - 1, I'll go with all. @michiels If you find that its really disturbing your workflow, we can always go back to the old way, ok?

**Comment by michiels** [comment]
Jep! Let's do this.
