### ISSUE TITLE
Add font-awesome-sass

### ISSUE THREAD

**Issue by jvanbaarsen** [firmhouse/Startblock#43]

**Comment by michiels** [comment]
This should probably be font-awesome-sass!

**Comment by jvanbaarsen** [comment]
@michiels What is the difference?

**Comment by michiels** [comment]
font-awesome-rails is the non-default and non-official gem created by bokkman: https://github.com/bokmann/font-awesome-rails
font-awesome-sass is the default and official gem by the creators of FontAwesome: https://github.com/FortAwesome/font-awesome-sass

The syntax of the two projects also slightly differs.

**Comment by jvanbaarsen** [comment]
:+1:
